services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Threeam\ThreeamFreeContentMode\ContextMenu\FreeContentModeItemProvider:
    tags:
      - name: backend.contextmenu.itemprovider